services:
  # Fetch videos/comments data
  comments:
    build:
      context: ./images/comments
      args:
        USERID: "${USERID:-0}"
        GROUPID: "${GROUPID:-0}"
    user: "${USERID:-0}:${GROUPID:-0}"
    container_name: comments
    volumes:
      - ./data:/app/data:rw
    env_file: conf.env

  # Compute sentiment and topic info
  sentiment-topic:
    build:
      context: ./images/sentiment-topic
      args:
        USERID: "${USERID:-0}"
        GROUPID: "${GROUPID:-0}"
    user: "${USERID:-0}:${GROUPID:-0}"
    container_name: sentiment-topic
    volumes:
      - ./data:/app/data:rw
    env_file: conf.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  # Run the streamlit app (if MODE=run) or rebuild the database
  # it uses (if MODE=refresh)
  streamlit:
    build:
      context: ./images/streamlit
      args:
        USERID: "${USERID:-0}"
        GROUPID: "${GROUPID:-0}"
    user: "${USERID:-0}:${GROUPID:-0}"
    environment:
      - MODE=${MODE:-run}
    container_name: streamlit
    hostname: streamlit
    networks:
      - stack
    ports:
      - target: 8504
        published: 8504
        protocol: tcp
        mode: host
    volumes:
      - ./data:/app/data:rw
    restart: on-failure
    env_file: conf.env

networks:
  stack:
    driver: bridge
